[project]
name = "chat-with-knowledge-graphs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "langchain",
    "langchain-anthropic",
    "langchain-community",
    "langchain-google-genai",
    "langchain-huggingface",
    "langchain-openai",
    "langgraph",
    "langgraph-checkpoint-redis>=0.1.1",
    "langgraph-checkpoint-sqlite>=2.0.11",
    "langgraph-cli[inmem]",
    "langgraph-prebuilt",
    "langgraph-sdk",
    "langsmith",
    "neo4j",
    "neomodel",
    "notebook",
    "streamlit",
    "tavily-python",
    "trustcall",
    "wikipedia",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "ruff>=0.14.2",
]

[tool.ruff]
line-length = 120
target-version = "py313"
exclude = ["venv/", ".venv/", "env/", ".env/"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "C4"]
ignore = ["E501"]
"__init__.py" = ["F401"] 

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
warn_return_any = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true
exclude = "venv/|.venv/|env/|.env/"
ignore_missing_imports = true 
